openapi: 3.0.3
info:
  title: Ecommerce - OpenAPI 3.0
  version: 1.0.11
tags:
  - name: article
    description: Everything about articles
paths:
  /article:
    get:
        tags:
          - article
        summary: Get all articles
        responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int64
                        example: 10    
                      name:
                        type: string
          '400':
            description: Invalid ID supplied
          '404':
            description: Article not found
    post:
      tags:
        - article
      summary: Save a new article
      requestBody:
        content:
            application/json:
              schema:
                type: object
                properties:
                    name:
                      type: string
                      example: chaise
                    description:
                      type: string
                      example: sert à s'assoir
                    price:
                      type: number
                      description: prix en centimes
                      example: 2000    
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 10    
        '400':
          description: Invalid ID supplied
        '404':
          description: Article not found
          
  /article/{id}:
    get:
      tags:
        - article
      summary: Get an article
      parameters:
        - name: id
          in: path
          description: ID article
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Article not found
    delete:
      tags:
        - article
      summary: Get an article
      parameters:
        - name: id
          in: path
          description: ID article
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Article not found
components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: chaise
        description:
          type: string
          example: http://chaise.jpg
        price:
          type: number
          description: prix en centimes
          example: 2000
     